package com.example.newscheezycodes

class HMap {
    var hmap = HashMap<String, String>()
    constructor(){
        hmap.put("\n\nUAE", "ae")
        hmap.put("\n\nRUSSIA", "ru")
        hmap.put("\n\nAUSTRALIA", "au")
        hmap.put("\n\nAUSTRIA", "at")
        hmap.put("\n\nBULGARIA", "bg")
        hmap.put("\n\nBELGIUM", "be")
        hmap.put("\n\nBRAZIL", "br")
        hmap.put("\n\nCANADA", "ca")
        hmap.put("\n\nSWITZERLAND", "ch")
        hmap.put("\n\nCHINA", "cn")
        hmap.put("\n\nCOLOMBIA", "co")
        hmap.put("\n\nCUBA", "cu")
        hmap.put("\n\nCZECHIA", "cz")
        hmap.put("\n\nGERMANY", "de")
        hmap.put("\n\nEGYPT", "eg")
        hmap.put("\n\nFRANCE", "fr")
        hmap.put("\n\nUNITED\nKINGDOM", "gb")
        hmap.put("\n\nGREECE", "gr")
        hmap.put("\n\nHONG\nKONG", "hk")
        hmap.put("\n\nHUNGARY", "hu")
        hmap.put("\n\nINDONESIA", "id")
        hmap.put("\n\nIRELAND", "ie")
        hmap.put("\n\nISRAEL", "il")
        hmap.put("\n\nITALY", "it")
        hmap.put("\n\nJAPAN", "jp")
        hmap.put("\n\nSOUTH\nKOREA", "kr")
        hmap.put("\n\nLITHUANIA", "lt")
        hmap.put("\n\nLATVIA", "lv")
        hmap.put("\n\nMOROCCO", "ma")
        hmap.put("\n\nMEXICO", "mx")
        hmap.put("\n\nMALAYSIA", "my")
        hmap.put("\n\nNIGERIA", "ng")
        hmap.put("\n\nNETHERLANDS", "nl")
        hmap.put("\n\nNORWAY", "no")
        hmap.put("\n\nNEW\nZEALAND", "nz")
        hmap.put("\n\nPHILIPPINES", "ph")
        hmap.put("\n\nPOLAND", "po")
        hmap.put("\n\nPORTUGAL", "pt")
        hmap.put("\n\nROMANIA", "ro")
        hmap.put("\n\nSERBIA", "rs")
        hmap.put("\n\nSAUDI\nARABIA", "sa")
        hmap.put("\n\nSWEDEN", "se")
        hmap.put("\n\nSINGAPORE", "sg")
        hmap.put("\n\nSLOVENIA", "si")
        hmap.put("\n\nSLOVAKIA", "sk")
        hmap.put("\n\nTHAILAND", "th")
        hmap.put("\n\nTURKEY", "tr")
        hmap.put("\n\nTAIWAN", "tw")
        hmap.put("\n\nUKRAINE", "ua")
        hmap.put("\n\nVENEZUELA", "ve")
        hmap.put("\n\nSOUTH\nAFRICA", "za")
    }
    fun getCountryCode(country:String):String{
        return hmap.get(country)!!
    }
}